name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: pmdMain spotlessJavaCheck build

      - name: PMD report
        uses: jwgmeligmeyling/pmd-github-action@v1
        if: failure()
        with:
          path: '**/reports/pmd/main.xml'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/